name: Migration to production
on:
  push:
    branches: 
      - test
    paths-ignore:
      - '.github/workflows/**'
env:
  PROMOTION_BRANCH: migrate
jobs:
  incremental_migration:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
      - name: Set user name and email
        run: |
          git config user.name "${{ github.event.head_commit.committer.name }}"
          git config user.email "${{ github.event.head_commit.committer.email }}"
      - name: Reset promotion branch
        run: |
          git fetch origin ${{ github.sha }}
          git cherry-pick --allow-empty --strategy=recursive --strategy-option=theirs ${{ github.sha }}
      - name: Get commit message
        id: commit-message
        run: |
          echo "::set-output name=subject::$(git log -1 --format=%s ${{ github.sha }})"
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3.10.0
        with:
          committer: ${{ github.event.head_commit.committer.name }} <${{ github.event.head_commit.committer.email }}>
          author: ${{ github.event.head_commit.author.name }} <${{ github.event.head_commit.author.email }}>
          signoff: true
          branch: ${{ env.PROMOTION_BRANCH }}
          branch-suffix: random
          delete-branch: true
          title: ${{ steps.commit-message.outputs.subject }}
          # body: |
            # Update report
            # - Updated with *today's* date
            # - Auto-generated by [create-pull-request][1]

            # [1]: https://github.com/peter-evans/create-pull-request
          # draft: false
      - name: Check outputs
        run: |
          echo "Pull Request Numberd - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
  # batch_promotion:
  #   runs-on: ubuntu-20.04
  #   steps:
  #     - uses: actions/checkout@v2
  #       with:
  #         ref: main
  #     - name: Set user name and email
  #       run: |
  #         git config user.name "${{ github.event.head_commit.committer.name }}"
  #         git config user.email "${{ github.event.head_commit.committer.email }}"
  #     - name: Reset promotion branch
  #       run: |
  #         git fetch origin test:test
  #         git reset --hard test
  #     - name: Create Pull Request
  #       id: cpr
  #       uses: peter-evans/create-pull-request@v3.8.2
  #       with:
  #         committer: ${{ github.event.head_commit.committer.name }} <${{ github.event.head_commit.committer.email }}>
  #         author: ${{ github.event.head_commit.author.name }} <${{ github.event.head_commit.author.email }}>
  #         signoff: true
  #         branch: ${{ env.PROMOTION_BRANCH }}
  #         delete-branch: true
  #         title: Cumulated changes from test branch
  #         body: |
  #           # Update report
  #           - SHA: ${{ github.sha }}
  #     - name: Check outputs
  #       run: |
  #         echo "Pull Request Numberd - ${{ steps.cpr.outputs.pull-request-number }}"
  #         echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"